# Generated by Django 5.2.12 on 2026-03-05 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identifier'], name='fhir_api_pa_identif_e22e9a_idx'), models.Index(fields=['family_name', 'given_name'], name='fhir_api_pa_family__5af428_idx')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(choices=[('blood-pressure', 'Tension artérielle'), ('heart-rate', 'Fréquence cardiaque'), ('temperature', 'Température corporelle'), ('weight', 'Poids'), ('height', 'Taille')], max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fhir_api.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'effective_date'], name='fhir_api_ob_patient_01a02f_idx'), models.Index(fields=['observation_type', 'effective_date'], name='fhir_api_ob_observa_ddb3ff_idx')],
            },
        ),
    ]
