# Generated by Django 5.2.12 on 2026-03-05 21:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('role', models.CharField(choices=[('doctor', 'Médecin'), ('nurse', 'Infirmier(e)'), ('pharmacist', 'Pharmacien(ne)'), ('physiotherapist', 'Kinésithérapeute'), ('specialist', 'Spécialiste'), ('other', 'Autre')], default='doctor', max_length=50)),
                ('rpps_number', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['family_name', 'given_name'], name='fhir_api_pr_family__9f5120_idx'), models.Index(fields=['role'], name='fhir_api_pr_role_3c35dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in-progress', 'En cours'), ('finished', 'Terminée'), ('cancelled', 'Annulée'), ('unknown', 'Inconnue')], default='planned', max_length=20)),
                ('encounter_class', models.CharField(choices=[('AMB', 'Ambulatoire'), ('IMP', 'Hospitalisation'), ('EMER', 'Urgences'), ('HH', 'Soins à domicile')], default='AMB', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Raison de la consultation')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='fhir_api.patient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='fhir_api.practitioner')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'start_date'], name='fhir_api_en_patient_e21077_idx'), models.Index(fields=['practitioner', 'start_date'], name='fhir_api_en_practit_068369_idx'), models.Index(fields=['status'], name='fhir_api_en_status_5d59d8_idx')],
            },
        ),
    ]
